# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AdminSPtoAzure'
    subscriptionId: 'bf72c8b6-4a01-43eb-a782-675774930974'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'armrg01'
    location: 'East Asia'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/rachod/armproj/main/create_web_app/azuredeploy.json'
    overrideParameters: '-projectName armproj'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'